-- ─────────────────────────────────────────────────────────────────────────────
-- V1__create_users_schema.sql
--
-- LEARNING POINT — Flyway naming convention:
--   V{version}__{description}.sql    (versioned — runs once, in order)
--   R__{description}.sql             (repeatable — runs whenever content changes)
--   U{version}__{description}.sql    (undo — for rollback, requires Flyway Teams)
--
-- Rules:
--   • NEVER modify an existing migration. Add a new V{n+1}__ file instead.
--   • Each migration runs in a transaction (Flyway rolls back on failure).
--   • Flyway tracks applied migrations in the "flyway_schema_history" table.
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable UUID generation function
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─────────────────────────────────────────────────────────────────────────────
-- Table: users
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users
(
    -- Primary key: UUID generated by PostgreSQL (or Hibernate's UUID strategy)
    id                      UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Identity
    username                VARCHAR(50)  NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    password                VARCHAR(255) NOT NULL,  -- BCrypt hash

    -- Profile
    first_name              VARCHAR(100),
    last_name               VARCHAR(100),
    phone_number            VARCHAR(20),
    profile_image_url       TEXT,

    -- Status
    status                  VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    email_verified          BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Security
    failed_login_attempts   INT          NOT NULL DEFAULT 0,
    locked_until            TIMESTAMP,

    -- Audit
    created_at              TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP    NOT NULL DEFAULT NOW(),
    last_login_at           TIMESTAMP,

    -- Constraints
    CONSTRAINT chk_status CHECK (status IN ('ACTIVE','INACTIVE','SUSPENDED','PENDING_VERIFY'))
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Table: user_roles  (ElementCollection join table)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_roles
(
    user_id  UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role     VARCHAR(30) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT chk_role CHECK (role IN ('ROLE_CUSTOMER','ROLE_SELLER','ROLE_ADMIN'))
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Indexes
-- ─────────────────────────────────────────────────────────────────────────────

-- Unique constraints enforce business rules at the DB level (second line of defence)
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email    ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- Index on status for admin queries (filter by ACTIVE, SUSPENDED, etc.)
CREATE INDEX IF NOT EXISTS idx_users_status    ON users(status);
CREATE INDEX IF NOT EXISTS idx_users_created   ON users(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- Trigger: auto-update updated_at on every UPDATE
--
-- LEARNING POINT: Without this trigger, updated_at would only be set by
-- Hibernate's @UpdateTimestamp. The trigger is a DB-level safety net.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION fn_update_updated_at();
