spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/orderdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      pool-name: OrderServicePool
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      product-service:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

server:
  port: ${SERVER_PORT:8082}
